#!/bin/bash

# 使用 `envsubst` 将模板文件中的 ${NGINX_PORT} 替换为实际的环境变量值
envsubst '${NGINX_PORT}${PORT}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
# 自动更新
cd /
/usr/local/bin/mp_update
cd /app
# 更改 naspilot userid 和 groupid
groupmod -o -g ${PGID} naspilot
usermod -o -u ${PUID} naspilot
# 更改文件权限
chown -R naspilot:naspilot \
    ${HOME} \
    /app \
    /public \
    /config \
    /var/lib/nginx \
    /var/log/nginx
chown naspilot:naspilot /etc/hosts /tmp
# 下载浏览器内核
gosu naspilot:naspilot playwright install chromium
# 启动前端nginx服务
nginx
# 启动haproxy
if [ -S "/var/run/docker.sock" ]; then
    haproxy -f /app/haproxy.cfg
fi
# 设置后端服务权限掩码
umask ${UMASK}
# 启动后端服务
exec dumb-init gosu naspilot:naspilot python3 app/main.py
