blank_issues_enabled: false
contact_links:
  - name: 项目讨论
    url: https://github.com/fortunearterial/NasPilot-Backend/discussions/new/choose
    about: discussion
  - name: Telegram 频道
    url: https://t.me/NasPilot_channel
    about: 更新日志
  - name: Telegram 交流群
    url: https://t.me/NasPilot_official
    about: 交流互助
