"""ly1.0.7

Revision ID: 10086e537bbd
Revises: 760bfd673e6c
Create Date: 2023-12-21 11:58:14.715446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10086e537bbd'
down_revision = '760bfd673e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('downloader', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'downloader')
    # ### end Alembic commands ###
