"""3.0.0.4

Revision ID: 36c6cf7084a6
Revises: 85f8087c0be0
Create Date: 2025-03-31 21:05:19.681935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c6cf7084a6'
down_revision = '85f8087c0be0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribehistory_bangumiid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_doubanid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_id', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_javdbid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_mediaid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_name', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_steamid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_tmdbid', table_name='subscribehistory')
    op.drop_table('subscribehistory')
    op.create_index(op.f('ix_userjob_id'), 'userjob', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userjob_id'), table_name='userjob')
    op.create_table('subscribehistory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('year', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('keyword', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tmdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imdbid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tvdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doubanid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bangumiid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steamid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('javdbid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('mediaid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('season', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('backdrop', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('vote', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('filter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('include', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('exclude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('resolution', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('effect', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sites', mysql.JSON(), nullable=True),
    sa.Column('best_version', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('save_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('search_imdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_words', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('media_category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('filter_groups', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subscribehistory_tmdbid', 'subscribehistory', ['tmdbid'], unique=False)
    op.create_index('ix_subscribehistory_steamid', 'subscribehistory', ['steamid'], unique=False)
    op.create_index('ix_subscribehistory_name', 'subscribehistory', ['name'], unique=False)
    op.create_index('ix_subscribehistory_mediaid', 'subscribehistory', ['mediaid'], unique=False)
    op.create_index('ix_subscribehistory_javdbid', 'subscribehistory', ['javdbid'], unique=False)
    op.create_index('ix_subscribehistory_id', 'subscribehistory', ['id'], unique=False)
    op.create_index('ix_subscribehistory_doubanid', 'subscribehistory', ['doubanid'], unique=False)
    op.create_index('ix_subscribehistory_bangumiid', 'subscribehistory', ['bangumiid'], unique=False)
    # ### end Alembic commands ###
