"""ly1.0.5

Revision ID: 3762bc8215d8
Revises: 80ce004d2401
Create Date: 2023-12-15 00:44:24.906080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3762bc8215d8'
down_revision = '80ce004d2401'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloadhistory', sa.Column('steamid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_downloadhistory_steamid'), 'downloadhistory', ['steamid'], unique=False)
    op.add_column('subscribe', sa.Column('steamid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subscribe_steamid'), 'subscribe', ['steamid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribe_steamid'), table_name='subscribe')
    op.drop_column('subscribe', 'steamid')
    op.drop_index(op.f('ix_downloadhistory_steamid'), table_name='downloadhistory')
    op.drop_column('downloadhistory', 'steamid')
    # ### end Alembic commands ###
