"""ly1.0.9

Revision ID: 4b6791f206b3
Revises: e7e55e98b593
Create Date: 2024-07-27 04:50:18.905764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6791f206b3'
down_revision = 'e7e55e98b593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_downloadhistory_tmdbid'), 'downloadhistory', ['tmdbid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloadhistory_tmdbid'), table_name='downloadhistory')
    # ### end Alembic commands ###
