"""ly1.1.0

Revision ID: 8c4da0bcb056
Revises: 4b6791f206b3
Create Date: 2024-08-17 09:52:34.602661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4da0bcb056'
down_revision = '4b6791f206b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
