"""ly1.0.2

Revision ID: 964e314eb282
Revises: d047ea6f9c22
Create Date: 2023-12-11 02:06:35.437663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964e314eb282'
down_revision = 'd047ea6f9c22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('rss', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'rss')
    # ### end Alembic commands ###
