"""ly1.0.3

Revision ID: b4a0865028f5
Revises: 964e314eb282
Create Date: 2023-12-11 09:04:12.028688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4a0865028f5'
down_revision = '964e314eb282'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'rss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('rss', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
