"""ly1.0.1

Revision ID: d047ea6f9c22
Revises: adcddcedd8b8
Create Date: 2023-12-08 03:21:20.521143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd047ea6f9c22'
down_revision = 'adcddcedd8b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('types', sa.JSON(), nullable=True))
    op.add_column('site', sa.Column('feed', sa.JSON(), nullable=True))
    op.add_column('site', sa.Column('search', sa.JSON(), nullable=True))
    op.add_column('site', sa.Column('xpath', sa.String(length=2000), nullable=True))
    op.drop_column('site', 'rss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('rss', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('site', 'xpath')
    op.drop_column('site', 'search')
    op.drop_column('site', 'feed')
    op.drop_column('site', 'types')
    # ### end Alembic commands ###
