"""2.9.9.1

Revision ID: d35debf98098
Revises: 4b544f5d3b07
Create Date: 2025-04-27 10:47:10.665514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd35debf98098'
down_revision = '4b544f5d3b07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_domain', table_name='site_copy1')
    op.drop_index('ix_site_id', table_name='site_copy1')
    op.drop_table('site_copy1')
    op.drop_index('ix_subscribe_bangumiid', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_doubanid', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_id', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_javdbid', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_mediaid', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_name', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_state', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_steamid', table_name='subscribe_copy1')
    op.drop_index('ix_subscribe_tmdbid', table_name='subscribe_copy1')
    op.drop_table('subscribe_copy1')
    op.drop_index('ix_subscribehistory_bangumiid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_doubanid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_id', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_javdbid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_mediaid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_name', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_steamid', table_name='subscribehistory')
    op.drop_index('ix_subscribehistory_tmdbid', table_name='subscribehistory')
    op.drop_table('subscribehistory')
    op.drop_column('subscribe', 'episode_groups')
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('recommend_code', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('invite_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invite_code')
    op.drop_column('user', 'recommend_code')
    op.drop_column('user', 'phone')
    op.add_column('subscribe', sa.Column('episode_groups', mysql.JSON(), nullable=True))
    op.create_table('subscribehistory',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('year', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=4), nullable=True),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('keyword', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('tmdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imdbid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('tvdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doubanid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('bangumiid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steamid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('javdbid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True),
    sa.Column('mediaid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('season', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2000), nullable=True),
    sa.Column('backdrop', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2000), nullable=True),
    sa.Column('vote', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('filter', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('include', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('exclude', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('quality', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('resolution', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('effect', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('total_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('username', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('sites', mysql.JSON(), nullable=True),
    sa.Column('best_version', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('save_path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('search_imdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_words', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('media_category', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('filter_groups', mysql.JSON(), nullable=True),
    sa.Column('episode_group', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subscribehistory_tmdbid', 'subscribehistory', ['tmdbid'], unique=False)
    op.create_index('ix_subscribehistory_steamid', 'subscribehistory', ['steamid'], unique=False)
    op.create_index('ix_subscribehistory_name', 'subscribehistory', ['name'], unique=False)
    op.create_index('ix_subscribehistory_mediaid', 'subscribehistory', ['mediaid'], unique=False)
    op.create_index('ix_subscribehistory_javdbid', 'subscribehistory', ['javdbid'], unique=False)
    op.create_index('ix_subscribehistory_id', 'subscribehistory', ['id'], unique=False)
    op.create_index('ix_subscribehistory_doubanid', 'subscribehistory', ['doubanid'], unique=False)
    op.create_index('ix_subscribehistory_bangumiid', 'subscribehistory', ['bangumiid'], unique=False)
    op.create_table('subscribe_copy1',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('year', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('keyword', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('tmdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imdbid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('tvdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doubanid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('steamid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('javdbid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True),
    sa.Column('bangumiid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mediaid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('season', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('backdrop', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('vote', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('filter', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('include', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('exclude', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('quality', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('resolution', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('effect', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('total_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lack_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.JSON(), nullable=True),
    sa.Column('state', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('last_update', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('date', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('sites', mysql.JSON(), nullable=True),
    sa.Column('best_version', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_priority', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('save_path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=2000), nullable=True),
    sa.Column('search_imdbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manual_total_episode', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_words', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('media_category', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('filter_groups', mysql.JSON(), nullable=True),
    sa.Column('episode_groups', mysql.JSON(), nullable=True),
    sa.Column('episode_group', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subscribe_tmdbid', 'subscribe_copy1', ['tmdbid'], unique=False)
    op.create_index('ix_subscribe_steamid', 'subscribe_copy1', ['steamid'], unique=False)
    op.create_index('ix_subscribe_state', 'subscribe_copy1', ['state'], unique=False)
    op.create_index('ix_subscribe_name', 'subscribe_copy1', ['name'], unique=False)
    op.create_index('ix_subscribe_mediaid', 'subscribe_copy1', ['mediaid'], unique=False)
    op.create_index('ix_subscribe_javdbid', 'subscribe_copy1', ['javdbid'], unique=False)
    op.create_index('ix_subscribe_id', 'subscribe_copy1', ['id'], unique=False)
    op.create_index('ix_subscribe_doubanid', 'subscribe_copy1', ['doubanid'], unique=False)
    op.create_index('ix_subscribe_bangumiid', 'subscribe_copy1', ['bangumiid'], unique=False)
    op.create_table('site_copy1',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('domain', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('types', mysql.JSON(), nullable=True),
    sa.Column('pri', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rss', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('rss_mapping', mysql.JSON(), nullable=True),
    sa.Column('browse', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('browse_method', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True),
    sa.Column('browse_config', mysql.JSON(), nullable=True),
    sa.Column('search', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('search_method', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True),
    sa.Column('search_config', mysql.JSON(), nullable=True),
    sa.Column('cookie', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('ua', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('apikey', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('token', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('proxy', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filter', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('render', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('public', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.JSON(), nullable=True),
    sa.Column('limit_interval', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit_seconds', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeout', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lst_mod_date', mysql.DATETIME(), nullable=True),
    sa.Column('downloader', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_site_id', 'site_copy1', ['id'], unique=False)
    op.create_index('ix_site_domain', 'site_copy1', ['domain'], unique=False)
    # ### end Alembic commands ###
