"""ly1.0.8

Revision ID: e7e55e98b593
Revises: 10086e537bbd
Create Date: 2024-06-20 09:11:34.078611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e55e98b593'
down_revision = '10086e537bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('apikey', sa.String(length=255), nullable=True))
    op.add_column('site', sa.Column('token', sa.String(length=255), nullable=True))
    op.add_column('site', sa.Column('timeout', sa.Integer(), nullable=True))
    op.add_column('subscribe', sa.Column('bangumiid', sa.Integer(), nullable=True))
    op.add_column('subscribe', sa.Column('search_imdbid', sa.Integer(), nullable=True))
    op.add_column('subscribe', sa.Column('manual_total_episode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscribe_bangumiid'), 'subscribe', ['bangumiid'], unique=False)
    op.add_column('user', sa.Column('is_otp', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('otp_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    op.drop_column('user', 'is_otp')
    op.drop_index(op.f('ix_subscribe_bangumiid'), table_name='subscribe')
    op.drop_column('subscribe', 'manual_total_episode')
    op.drop_column('subscribe', 'search_imdbid')
    op.drop_column('subscribe', 'bangumiid')
    op.drop_column('site', 'timeout')
    op.drop_column('site', 'token')
    op.drop_column('site', 'apikey')
    # ### end Alembic commands ###
